--- #YAML:1.0
name:                B-Lint
version:             1.10
abstract:            Perl lint
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Module::Pluggable:             0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Joshua ben Jore <jjore@cpan.org>
